CREATE TABLE adopter (
	adopter_id int IDENTITY(1001,1) primary key NOT NULL,
	name varchar(200) NULL,
	street_number varchar(50) NULL,
	street_name varchar(200) NULL,
	city varchar(100) NULL,
	state varchar(50) NULL,
	zip_code int NULL,
	phone_num varchar(20) NULL,
	email varchar(100) NULL,
	species_desired varchar(100) NULL,
	lifestyle_traits int NOT NULL,
	residence_ownership_status varchar(50) NULL,
	allergies varchar(10) NULL,
	previous_pets varchar(100) NULL,
	current_pets varchar(100) NULL,
	veterinarian int NULL,
	home_visit_possibility varchar(20) NULL,
)
