#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumaneSocietyApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HumaneSociety")]
	public partial class HumaneSocietyDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadopter(adopter instance);
    partial void Updateadopter(adopter instance);
    partial void Deleteadopter(adopter instance);
    partial void Insertanimal(animal instance);
    partial void Updateanimal(animal instance);
    partial void Deleteanimal(animal instance);
    partial void Insertveterinarian(veterinarian instance);
    partial void Updateveterinarian(veterinarian instance);
    partial void Deleteveterinarian(veterinarian instance);
    partial void Insertvisit(visit instance);
    partial void Updatevisit(visit instance);
    partial void Deletevisit(visit instance);
    #endregion
		
		public HumaneSocietyDBDataContext() : 
				base(global::HumaneSocietyApp.Properties.Settings.Default.HumaneSocietyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HumaneSocietyDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HumaneSocietyDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HumaneSocietyDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HumaneSocietyDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<adopter> adopters
		{
			get
			{
				return this.GetTable<adopter>();
			}
		}
		
		public System.Data.Linq.Table<animal> animals
		{
			get
			{
				return this.GetTable<animal>();
			}
		}
		
		public System.Data.Linq.Table<veterinarian> veterinarians
		{
			get
			{
				return this.GetTable<veterinarian>();
			}
		}
		
		public System.Data.Linq.Table<visit> visits
		{
			get
			{
				return this.GetTable<visit>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.adopter")]
	public partial class adopter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _adopter_id;
		
		private string _name;
		
		private string _street_number;
		
		private System.Nullable<int> _street_name;
		
		private string _city;
		
		private string _state;
		
		private string _zip_code;
		
		private string _phone_num;
		
		private string _email;
		
		private string _species_desired;
		
		private string _lifestyle_traits;
		
		private string _residence_ownership_status;
		
		private string _allergies;
		
		private System.Nullable<int> _previous_pets;
		
		private System.Nullable<int> _current_pets;
		
		private System.Nullable<int> _veterinarian;
		
		private string _home_visit_possibility;
		
		private EntitySet<visit> _visits;
		
		private EntityRef<veterinarian> _veterinarian1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onadopter_idChanging(int value);
    partial void Onadopter_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onstreet_numberChanging(string value);
    partial void Onstreet_numberChanged();
    partial void Onstreet_nameChanging(System.Nullable<int> value);
    partial void Onstreet_nameChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void Onzip_codeChanging(string value);
    partial void Onzip_codeChanged();
    partial void Onphone_numChanging(string value);
    partial void Onphone_numChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onspecies_desiredChanging(string value);
    partial void Onspecies_desiredChanged();
    partial void Onlifestyle_traitsChanging(string value);
    partial void Onlifestyle_traitsChanged();
    partial void Onresidence_ownership_statusChanging(string value);
    partial void Onresidence_ownership_statusChanged();
    partial void OnallergiesChanging(string value);
    partial void OnallergiesChanged();
    partial void Onprevious_petsChanging(System.Nullable<int> value);
    partial void Onprevious_petsChanged();
    partial void Oncurrent_petsChanging(System.Nullable<int> value);
    partial void Oncurrent_petsChanged();
    partial void OnveterinarianChanging(System.Nullable<int> value);
    partial void OnveterinarianChanged();
    partial void Onhome_visit_possibilityChanging(string value);
    partial void Onhome_visit_possibilityChanged();
    #endregion
		
		public adopter()
		{
			this._visits = new EntitySet<visit>(new Action<visit>(this.attach_visits), new Action<visit>(this.detach_visits));
			this._veterinarian1 = default(EntityRef<veterinarian>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adopter_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int adopter_id
		{
			get
			{
				return this._adopter_id;
			}
			set
			{
				if ((this._adopter_id != value))
				{
					this.Onadopter_idChanging(value);
					this.SendPropertyChanging();
					this._adopter_id = value;
					this.SendPropertyChanged("adopter_id");
					this.Onadopter_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(200)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street_number", DbType="VarChar(50)")]
		public string street_number
		{
			get
			{
				return this._street_number;
			}
			set
			{
				if ((this._street_number != value))
				{
					this.Onstreet_numberChanging(value);
					this.SendPropertyChanging();
					this._street_number = value;
					this.SendPropertyChanged("street_number");
					this.Onstreet_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street_name", DbType="Int")]
		public System.Nullable<int> street_name
		{
			get
			{
				return this._street_name;
			}
			set
			{
				if ((this._street_name != value))
				{
					this.Onstreet_nameChanging(value);
					this.SendPropertyChanging();
					this._street_name = value;
					this.SendPropertyChanged("street_name");
					this.Onstreet_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(100)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(50)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip_code", DbType="VarChar(50)")]
		public string zip_code
		{
			get
			{
				return this._zip_code;
			}
			set
			{
				if ((this._zip_code != value))
				{
					this.Onzip_codeChanging(value);
					this.SendPropertyChanging();
					this._zip_code = value;
					this.SendPropertyChanged("zip_code");
					this.Onzip_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_num", DbType="VarChar(20)")]
		public string phone_num
		{
			get
			{
				return this._phone_num;
			}
			set
			{
				if ((this._phone_num != value))
				{
					this.Onphone_numChanging(value);
					this.SendPropertyChanging();
					this._phone_num = value;
					this.SendPropertyChanged("phone_num");
					this.Onphone_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_species_desired", DbType="VarChar(100)")]
		public string species_desired
		{
			get
			{
				return this._species_desired;
			}
			set
			{
				if ((this._species_desired != value))
				{
					this.Onspecies_desiredChanging(value);
					this.SendPropertyChanging();
					this._species_desired = value;
					this.SendPropertyChanged("species_desired");
					this.Onspecies_desiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lifestyle_traits", DbType="VarChar(200)")]
		public string lifestyle_traits
		{
			get
			{
				return this._lifestyle_traits;
			}
			set
			{
				if ((this._lifestyle_traits != value))
				{
					this.Onlifestyle_traitsChanging(value);
					this.SendPropertyChanging();
					this._lifestyle_traits = value;
					this.SendPropertyChanged("lifestyle_traits");
					this.Onlifestyle_traitsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_residence_ownership_status", DbType="VarChar(50)")]
		public string residence_ownership_status
		{
			get
			{
				return this._residence_ownership_status;
			}
			set
			{
				if ((this._residence_ownership_status != value))
				{
					this.Onresidence_ownership_statusChanging(value);
					this.SendPropertyChanging();
					this._residence_ownership_status = value;
					this.SendPropertyChanged("residence_ownership_status");
					this.Onresidence_ownership_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_allergies", DbType="VarChar(10)")]
		public string allergies
		{
			get
			{
				return this._allergies;
			}
			set
			{
				if ((this._allergies != value))
				{
					this.OnallergiesChanging(value);
					this.SendPropertyChanging();
					this._allergies = value;
					this.SendPropertyChanged("allergies");
					this.OnallergiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_previous_pets", DbType="Int")]
		public System.Nullable<int> previous_pets
		{
			get
			{
				return this._previous_pets;
			}
			set
			{
				if ((this._previous_pets != value))
				{
					this.Onprevious_petsChanging(value);
					this.SendPropertyChanging();
					this._previous_pets = value;
					this.SendPropertyChanged("previous_pets");
					this.Onprevious_petsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_current_pets", DbType="Int")]
		public System.Nullable<int> current_pets
		{
			get
			{
				return this._current_pets;
			}
			set
			{
				if ((this._current_pets != value))
				{
					this.Oncurrent_petsChanging(value);
					this.SendPropertyChanging();
					this._current_pets = value;
					this.SendPropertyChanged("current_pets");
					this.Oncurrent_petsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veterinarian", DbType="Int")]
		public System.Nullable<int> veterinarian
		{
			get
			{
				return this._veterinarian;
			}
			set
			{
				if ((this._veterinarian != value))
				{
					if (this._veterinarian1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnveterinarianChanging(value);
					this.SendPropertyChanging();
					this._veterinarian = value;
					this.SendPropertyChanged("veterinarian");
					this.OnveterinarianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_home_visit_possibility", DbType="VarChar(20)")]
		public string home_visit_possibility
		{
			get
			{
				return this._home_visit_possibility;
			}
			set
			{
				if ((this._home_visit_possibility != value))
				{
					this.Onhome_visit_possibilityChanging(value);
					this.SendPropertyChanging();
					this._home_visit_possibility = value;
					this.SendPropertyChanged("home_visit_possibility");
					this.Onhome_visit_possibilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="adopter_visit", Storage="_visits", ThisKey="adopter_id", OtherKey="adopter")]
		public EntitySet<visit> visits
		{
			get
			{
				return this._visits;
			}
			set
			{
				this._visits.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="veterinarian_adopter", Storage="_veterinarian1", ThisKey="veterinarian", OtherKey="veterinarian_id", IsForeignKey=true)]
		public veterinarian veterinarian1
		{
			get
			{
				return this._veterinarian1.Entity;
			}
			set
			{
				veterinarian previousValue = this._veterinarian1.Entity;
				if (((previousValue != value) 
							|| (this._veterinarian1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._veterinarian1.Entity = null;
						previousValue.adopters.Remove(this);
					}
					this._veterinarian1.Entity = value;
					if ((value != null))
					{
						value.adopters.Add(this);
						this._veterinarian = value.veterinarian_id;
					}
					else
					{
						this._veterinarian = default(Nullable<int>);
					}
					this.SendPropertyChanged("veterinarian1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_visits(visit entity)
		{
			this.SendPropertyChanging();
			entity.adopter1 = this;
		}
		
		private void detach_visits(visit entity)
		{
			this.SendPropertyChanging();
			entity.adopter1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.animal")]
	public partial class animal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _animal_id;
		
		private string _name;
		
		private string _species;
		
		private string _is_vaccinated;
		
		private System.Nullable<double> _amount_of_food;
		
		private string _room;
		
		private string _is_adopted;
		
		private System.Nullable<int> _adoption_fee;
		
		private string _special_needs;
		
		private System.Nullable<int> _age;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onanimal_idChanging(int value);
    partial void Onanimal_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnspeciesChanging(string value);
    partial void OnspeciesChanged();
    partial void Onis_vaccinatedChanging(string value);
    partial void Onis_vaccinatedChanged();
    partial void Onamount_of_foodChanging(System.Nullable<double> value);
    partial void Onamount_of_foodChanged();
    partial void OnroomChanging(string value);
    partial void OnroomChanged();
    partial void Onis_adoptedChanging(string value);
    partial void Onis_adoptedChanged();
    partial void Onadoption_feeChanging(System.Nullable<int> value);
    partial void Onadoption_feeChanged();
    partial void Onspecial_needsChanging(string value);
    partial void Onspecial_needsChanged();
    partial void OnageChanging(System.Nullable<int> value);
    partial void OnageChanged();
    #endregion
		
		public animal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_animal_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int animal_id
		{
			get
			{
				return this._animal_id;
			}
			set
			{
				if ((this._animal_id != value))
				{
					this.Onanimal_idChanging(value);
					this.SendPropertyChanging();
					this._animal_id = value;
					this.SendPropertyChanged("animal_id");
					this.Onanimal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_species", DbType="VarChar(100)")]
		public string species
		{
			get
			{
				return this._species;
			}
			set
			{
				if ((this._species != value))
				{
					this.OnspeciesChanging(value);
					this.SendPropertyChanging();
					this._species = value;
					this.SendPropertyChanged("species");
					this.OnspeciesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_vaccinated", DbType="VarChar(5)")]
		public string is_vaccinated
		{
			get
			{
				return this._is_vaccinated;
			}
			set
			{
				if ((this._is_vaccinated != value))
				{
					this.Onis_vaccinatedChanging(value);
					this.SendPropertyChanging();
					this._is_vaccinated = value;
					this.SendPropertyChanged("is_vaccinated");
					this.Onis_vaccinatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount_of_food", DbType="Float")]
		public System.Nullable<double> amount_of_food
		{
			get
			{
				return this._amount_of_food;
			}
			set
			{
				if ((this._amount_of_food != value))
				{
					this.Onamount_of_foodChanging(value);
					this.SendPropertyChanging();
					this._amount_of_food = value;
					this.SendPropertyChanged("amount_of_food");
					this.Onamount_of_foodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room", DbType="VarChar(100)")]
		public string room
		{
			get
			{
				return this._room;
			}
			set
			{
				if ((this._room != value))
				{
					this.OnroomChanging(value);
					this.SendPropertyChanging();
					this._room = value;
					this.SendPropertyChanged("room");
					this.OnroomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_adopted", DbType="VarChar(10)")]
		public string is_adopted
		{
			get
			{
				return this._is_adopted;
			}
			set
			{
				if ((this._is_adopted != value))
				{
					this.Onis_adoptedChanging(value);
					this.SendPropertyChanging();
					this._is_adopted = value;
					this.SendPropertyChanged("is_adopted");
					this.Onis_adoptedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adoption_fee", DbType="Int")]
		public System.Nullable<int> adoption_fee
		{
			get
			{
				return this._adoption_fee;
			}
			set
			{
				if ((this._adoption_fee != value))
				{
					this.Onadoption_feeChanging(value);
					this.SendPropertyChanging();
					this._adoption_fee = value;
					this.SendPropertyChanged("adoption_fee");
					this.Onadoption_feeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_special_needs", DbType="VarChar(5)")]
		public string special_needs
		{
			get
			{
				return this._special_needs;
			}
			set
			{
				if ((this._special_needs != value))
				{
					this.Onspecial_needsChanging(value);
					this.SendPropertyChanging();
					this._special_needs = value;
					this.SendPropertyChanged("special_needs");
					this.Onspecial_needsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_age", DbType="Int")]
		public System.Nullable<int> age
		{
			get
			{
				return this._age;
			}
			set
			{
				if ((this._age != value))
				{
					this.OnageChanging(value);
					this.SendPropertyChanging();
					this._age = value;
					this.SendPropertyChanged("age");
					this.OnageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.veterinarian")]
	public partial class veterinarian : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _veterinarian_id;
		
		private string _name;
		
		private string _clinic;
		
		private string _street_number;
		
		private System.Nullable<int> _street_name;
		
		private string _city;
		
		private string _state;
		
		private string _zip_code;
		
		private string _phone_num;
		
		private string _email;
		
		private EntitySet<adopter> _adopters;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onveterinarian_idChanging(int value);
    partial void Onveterinarian_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnclinicChanging(string value);
    partial void OnclinicChanged();
    partial void Onstreet_numberChanging(string value);
    partial void Onstreet_numberChanged();
    partial void Onstreet_nameChanging(System.Nullable<int> value);
    partial void Onstreet_nameChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void Onzip_codeChanging(string value);
    partial void Onzip_codeChanged();
    partial void Onphone_numChanging(string value);
    partial void Onphone_numChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public veterinarian()
		{
			this._adopters = new EntitySet<adopter>(new Action<adopter>(this.attach_adopters), new Action<adopter>(this.detach_adopters));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_veterinarian_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int veterinarian_id
		{
			get
			{
				return this._veterinarian_id;
			}
			set
			{
				if ((this._veterinarian_id != value))
				{
					this.Onveterinarian_idChanging(value);
					this.SendPropertyChanging();
					this._veterinarian_id = value;
					this.SendPropertyChanged("veterinarian_id");
					this.Onveterinarian_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(200)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_clinic", DbType="VarChar(200)")]
		public string clinic
		{
			get
			{
				return this._clinic;
			}
			set
			{
				if ((this._clinic != value))
				{
					this.OnclinicChanging(value);
					this.SendPropertyChanging();
					this._clinic = value;
					this.SendPropertyChanged("clinic");
					this.OnclinicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street_number", DbType="VarChar(50)")]
		public string street_number
		{
			get
			{
				return this._street_number;
			}
			set
			{
				if ((this._street_number != value))
				{
					this.Onstreet_numberChanging(value);
					this.SendPropertyChanging();
					this._street_number = value;
					this.SendPropertyChanged("street_number");
					this.Onstreet_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street_name", DbType="Int")]
		public System.Nullable<int> street_name
		{
			get
			{
				return this._street_name;
			}
			set
			{
				if ((this._street_name != value))
				{
					this.Onstreet_nameChanging(value);
					this.SendPropertyChanging();
					this._street_name = value;
					this.SendPropertyChanged("street_name");
					this.Onstreet_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="VarChar(100)")]
		public string city
		{
			get
			{
				return this._city;
			}
			set
			{
				if ((this._city != value))
				{
					this.OncityChanging(value);
					this.SendPropertyChanging();
					this._city = value;
					this.SendPropertyChanged("city");
					this.OncityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(50)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zip_code", DbType="VarChar(50)")]
		public string zip_code
		{
			get
			{
				return this._zip_code;
			}
			set
			{
				if ((this._zip_code != value))
				{
					this.Onzip_codeChanging(value);
					this.SendPropertyChanging();
					this._zip_code = value;
					this.SendPropertyChanged("zip_code");
					this.Onzip_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_num", DbType="VarChar(20)")]
		public string phone_num
		{
			get
			{
				return this._phone_num;
			}
			set
			{
				if ((this._phone_num != value))
				{
					this.Onphone_numChanging(value);
					this.SendPropertyChanging();
					this._phone_num = value;
					this.SendPropertyChanged("phone_num");
					this.Onphone_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="veterinarian_adopter", Storage="_adopters", ThisKey="veterinarian_id", OtherKey="veterinarian")]
		public EntitySet<adopter> adopters
		{
			get
			{
				return this._adopters;
			}
			set
			{
				this._adopters.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_adopters(adopter entity)
		{
			this.SendPropertyChanging();
			entity.veterinarian1 = this;
		}
		
		private void detach_adopters(adopter entity)
		{
			this.SendPropertyChanging();
			entity.veterinarian1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.visit")]
	public partial class visit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _visit_id;
		
		private System.Nullable<int> _adopter;
		
		private string _species_desired;
		
		private EntityRef<adopter> _adopter1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onvisit_idChanging(int value);
    partial void Onvisit_idChanged();
    partial void OnadopterChanging(System.Nullable<int> value);
    partial void OnadopterChanged();
    partial void Onspecies_desiredChanging(string value);
    partial void Onspecies_desiredChanged();
    #endregion
		
		public visit()
		{
			this._adopter1 = default(EntityRef<adopter>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visit_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int visit_id
		{
			get
			{
				return this._visit_id;
			}
			set
			{
				if ((this._visit_id != value))
				{
					this.Onvisit_idChanging(value);
					this.SendPropertyChanging();
					this._visit_id = value;
					this.SendPropertyChanged("visit_id");
					this.Onvisit_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adopter", DbType="Int")]
		public System.Nullable<int> adopter
		{
			get
			{
				return this._adopter;
			}
			set
			{
				if ((this._adopter != value))
				{
					if (this._adopter1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnadopterChanging(value);
					this.SendPropertyChanging();
					this._adopter = value;
					this.SendPropertyChanged("adopter");
					this.OnadopterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_species_desired", DbType="VarChar(50)")]
		public string species_desired
		{
			get
			{
				return this._species_desired;
			}
			set
			{
				if ((this._species_desired != value))
				{
					this.Onspecies_desiredChanging(value);
					this.SendPropertyChanging();
					this._species_desired = value;
					this.SendPropertyChanged("species_desired");
					this.Onspecies_desiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="adopter_visit", Storage="_adopter1", ThisKey="adopter", OtherKey="adopter_id", IsForeignKey=true)]
		public adopter adopter1
		{
			get
			{
				return this._adopter1.Entity;
			}
			set
			{
				adopter previousValue = this._adopter1.Entity;
				if (((previousValue != value) 
							|| (this._adopter1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._adopter1.Entity = null;
						previousValue.visits.Remove(this);
					}
					this._adopter1.Entity = value;
					if ((value != null))
					{
						value.visits.Add(this);
						this._adopter = value.adopter_id;
					}
					else
					{
						this._adopter = default(Nullable<int>);
					}
					this.SendPropertyChanged("adopter1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
